package aula3.tratamentoerros.exceptions;

public class Desafio {
	public static void main(String[] args) {

	}
	
	
	
	
	
}
